name: server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  mongo_dart: ^0.8.2
  shelf: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
